version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wallet'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=user'
    ports:
      - '5433:5432'
