spring:
  application:
    name: auth-wallet-ms

  kafka:
    producer:
      bootstrap-servers: kafka+ssl://ec2-34-225-249-6.compute-1.amazonaws.com:9096,kafka+ssl://ec2-35-171-249-113.compute-1.amazonaws.com:9096,kafka+ssl://ec2-52-72-57-180.compute-1.amazonaws.com:9096,kafka+ssl://ec2-35-173-141-235.compute-1.amazonaws.com:9096,kafka+ssl://ec2-52-207-67-154.compute-1.amazonaws.com:9096,kafka+ssl://ec2-52-22-141-43.compute-1.amazonaws.com:9096,kafka+ssl://ec2-35-153-237-2.compute-1.amazonaws.com:9096,kafka+ssl://ec2-35-170-235-71.compute-1.amazonaws.com:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
#        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required \
#          username="${KAFKA_USERNAME}" \
#          password="${KAFKA_PASSWORD}";

    consumer:
      bootstrap-servers: kafka+ssl://ec2-34-225-249-6.compute-1.amazonaws.com:9096,kafka+ssl://ec2-35-171-249-113.compute-1.amazonaws.com:9096,kafka+ssl://ec2-52-72-57-180.compute-1.amazonaws.com:9096,kafka+ssl://ec2-35-173-141-235.compute-1.amazonaws.com:9096,kafka+ssl://ec2-52-207-67-154.compute-1.amazonaws.com:9096,kafka+ssl://ec2-52-22-141-43.compute-1.amazonaws.com:9096,kafka+ssl://ec2-35-153-237-2.compute-1.amazonaws.com:9096,kafka+ssl://ec2-35-170-235-71.compute-1.amazonaws.com:9096
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
#        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required \
#          username="${KAFKA_USERNAME}" \
#          password="${KAFKA_PASSWORD}";


  docker:
    compose:
      enabled: false

  mail:
    username: javidarkishiev@gmail.com
    password: feut yvtr ljbm dzbn
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          connection-timeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
        main:
          allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5433/wallet
    username: user
    password: 123456
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        store_data_at_delete: true
        #        default_schema:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        spring:
          liquibase:
            change-log=classpath:db/changelog/db:
              changelog-master:
                yaml:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true

server:
  port: ${PORT:9090}

jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000
