spring:
  application:
    name: auth-wallet-ms
  mail:
    username: javidarkishiev@gmail.com
    password: feut yvtr ljbm dzbn
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          connection-timeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
        main:
          allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5433/wallet
    username: user
    password: 123456
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        store_data_at_delete: true
        #        default_schema:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        spring:
          liquibase:
            change-log=classpath:db/changelog/db:
              changelog-master:
                yaml:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true

server:
  port: ${PORT:9090}

jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000