spring:
  application:
    name: auth-wallet-ms

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

  mail:
    username: javidarkishiev@gmail.com
    password: feut yvtr ljbm dzbn
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          connection-timeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5433/wallet
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        store_data_at_delete: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

server:
  port: ${PORT:9090}

jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000
